# Set working directory
setwd("C:/Monash/FIT3152")

# Load the given data
Dec21PedCount = read.csv("Ped_Count_December_2021.csv", header = TRUE)
Dec21PedCount = lapply(Dec21PedCount[3:83], as.numeric)
Dec21PedCount = as.data.frame(Dec21PedCount)

summary(Dec21PedCount)

################################################################################
################################################################################

nrow(Dec21PedCount) # 744 rows
ncol(Dec21PedCount) # 81 rows
dim(Dec21PedCount)

# 81 location representing all the location so the total amt of sensor location is 81

# Number of observations each day is 81x24 = 1944

# Average pedestrian count:
colMeans(Dec21PedCount, na.rm=TRUE) # Calculate all the mean for each column
# na.rm=TRUE to remove NA

# Boxplot
boxplot(Dec21PedCount, las=2)

# Time series
mc = ts(Dec21PedCount$Melbourne.Central, frequency = 24)
plot(mc)
mc_decom = decompose(mc)
plot(mc_decom)

################################################################################
################################################################################

# More application is appearing and AI is introduced to the peoples
# New ways to conduct crimes where people moved from physical crimes to cyber crimes
# Example like phishing emails
# People also moved from physical shopping to online shopping where the products people bought is directly delivered to their doorsteps
# People also moved on from going to library to find resources to just searching it online through the Internet

# Online shopping as during the pandemic people are not allowed to leave their homes
# How people communicated. Last time people go out to meet friends, now people can talk to their friends no matter the distance with the help of messaging apps

# Google
# 2018 only 3.7 Search Queries
# 2023 have 6.3 Search Queries
# Data collected is how dependant people are on the internet to serach for stuffs
# This shows people are more keen to have their problems solved online instead of finding the solution to their problems through the library and word of mouth

# Nothing is private anymore. 
# People willingly post their lives online for others to see. 
# So there is no longer private moments for loved ones or family; instead, everyone is exposed for judgement. 
# This creates anxiety in people who feel the need to make sure their life looks good on camera.

################################################################################
################################################################################

# Media companies face the challenge of attracting and retaining audiences in an increasingly competitive landscape. 
# They need to tailor their content and marketing efforts to individual 
# preferences to enhance engagement and drive revenue.

# Human-Generated Data 
# -> Descriptions of shows, series, and contributors that populate 
#    electronic program guides (EPGs), TV guides, and apps
# User-Generated Data
# -> Crowdsourced ratings on review sites and content owner platforms provide 
#    insights into audience preferences
#    Machine-Generated Data
# ->  Data generated by applications, devices, networks, and platforms that serve media content. 
#     This includes streaming services, websites and mobile apps

# Personalization Algorithms Analysis:
# Analyzing user-generated data (such as social media conversations and ratings) 
# to understand viewer preferences.
# Leveraging editorial metadata and machine-generated data to recommend relevant content to individual users.
# Real-time analytics to adapt recommendations based on user behavior.

# Improved Audience Engagement:
# Personalized marketing strategies lead to higher engagement rates.
# Recommendations based on user preferences increase content consumption.
# Social media sentiment analysis helps media companies understand audience reactions.

# Education aspects:
# Use personalized learning algorithms to recommend educational content based on individual student preferences.
# Analyze student engagement and learning outcomes to optimize educational experiences.

################################################################################
################################################################################

invest_a <- read.csv("InvestA.csv")
invest_b  <- read.csv("InvestB.csv")
toothbrush  <- read.csv("Toothbrush.csv")
workers  <- read.csv("Workers.csv")
food_retail  <- read.csv("Food Retail 2014-2020.csv")

################################################################################
################################################################################

pacific_lengths <- c(209, 48, 169, 138, 64, 97, 161, 95, 145, 90, 121, 80, 56, 64, 209, 64, 72, 288, 322)
tasman_lengths <- c(76, 64, 68, 64, 37, 32, 32, 51, 56, 40, 64, 56, 80, 121, 177, 56, 80, 35, 72, 72, 108, 48)

summary(pacific_lengths)
summary(tasman_lengths)

boxplot(pacific_lengths, tasman_lengths)
t.test(pacific_lengths, tasman_lengths, "greater", conf.level=0.99)

################################################################################
################################################################################

metacarp <- c(45, 51, 39, 41, 48, 49, 46, 43, 47)
stature <- c(171, 178, 157, 163, 172, 183, 173, 175, 173)
fitted = lm(stature ~ metacarp)
plot(metacarp, stature)
abline(fitted)
summary(fitted)

################################################################################
################################################################################

kiama_cliff <- read.table("http://www.statsci.org/data/oz/kiama.txt", header = TRUE)
summary(kiama_cliff)

################################################################################
################################################################################

timber <- read.table("http://www.statsci.org/data/oz/timber.txt", header = TRUE)
View(timber)
cor(timber)

fitted = lm(timber$Rigid ~ timber$Dens)
summary(fitted)

fitted = lm(timber$Rigid ~ timber$Dens + timber$Elast)
summary(fitted)

################################################################################
################################################################################

boxplot(invest_a$FV ~ invest_a$Group)
aggregate(invest_a$FV, by = list(invest_a$Group), FUN = "mean")

################################################################################
################################################################################
